### ISSUE TITLE
Possibilité de ne pas avoir de swap ?  ( et autres suggestions) 

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/archlinux-install#34]
Bonjour,
Félicitations pour ce script en python.
Je le teste actuellement.
Est-il possible d'avoir le choix de ne pas avoir de swap ? ( souvent inutile si ssd avec bcp de ram)
J'ai utilisé le partitionnement manuel.

Un truc intéressant aussi serait de décomposer gnome et xfce par exemple en donnant le choix des goodies ou pas pour xfce et extra ou pas pour gnome.

Voilà quelques suggestions supplémentaires. 🙂

Merci

**Comment by Rawleenc** [comment]
Bonsoir !

Merci pour ton retour et tes suggestions !

Concernant la possibilité de ne pas avoir de swap, actuellement ce n'est pas possible mais ça pourrais très simplement l'être en permettant par exemple d'entrer "0" à la question pour la taille du fichier de swap avec une gestion particulière dans ce cas.

Concernant la possibilité de décomposer l'installation des environnements, une possibilité simple et maintenable pourrais être de poser une question générique du style "Souhaitez-vous installer un environnement complet ? (O/n) :" ou bien "Souhaitez-vous installer un environnement minimal ? (o/N) :" pour tous les environnements décomposables.

Qu'en penses tu ?

**Comment by Neo-29** [comment]
Pour le swap à zéro j'ai essayé, ça n'a pas fonctionné.
Message d'erreur.
Pour minimal et complet c'est bonne idée. 🙂
Je partirais sur la question avec un environnement minimal en rajoutant peut être entre parenthèse "pour un environnement complet tapez N) pour être sûr sue ce soit bien compris.

**Comment by Rawleenc** [comment]
Oui le swap à zero ne fonctionne pas encore, j'ajouterais ça avec la question pour l'environnement minimal.

**Comment by Rawleenc** [comment]
Bonsoir,

Le swap à 0 est disponible sur la branche de développement.

La possibilité d'installer un environnement minimal est disponible pour les environnement gnome, plasma, xfce, deepin et mate sur la branche de développement.

N'hésite pas à fermer cette issue :wink:

**Comment by Neo-29** [comment]
Pas de swap à zéro proposé en partionnement auto.
On ne m'a pas proposé de taille 🤔

**Comment by Rawleenc** [comment]
Bonjour,
Ce n'est pas le but du partitionnement auto, son but n'est pas de proposer autant de flexibilité que le partitionnement manuelle, donc pas de choix de taille ni de choix de type de filesystem par partition, etc.

**Comment by Rawleenc** [comment]
À la limite, si c'est vraiment nécessaire, je pourrais rajouter une option 2: aucun a la question sur le type de swap, c'est simple a implémenter et ça n'entre pas en conflit avec le fonctionnement du partitionnement automatique.

**Comment by Neo-29** [comment]
> Bonjour, Ce n'est pas le but du partitionnement auto, son but n'est pas de proposer autant de flexibilité que le partitionnement manuelle, donc pas de choix de taille ni de choix de type de filesystem par partition, etc.

On est d'accord là dessus.

**Comment by Neo-29** [comment]
> Je pense que ce serait bien oui pour l'option 2 🙂



> À la limite, si c'est vraiment nécessaire, je pourrais rajouter une option 2: aucun a la question sur le type de swap, c'est simple a implémenter et ça n'entre pas en conflit avec le fonctionnement du partitionnement automatique.

Je pense que ce serait bien oui pour l'option 2 🙂

**Comment by Rawleenc** [comment]
Bonsoir,

L'option 2 afin de ne pas avoir de swap lors du partitionnement automatique est disponible sur la branche de développement !

**Comment by Neo-29** [comment]
> Bonsoir,
> 
> L'option 2 afin de ne pas avoir de swap lors du partitionnement automatique est disponible sur la branche de développement !

Top ! Merci !
