### ISSUE TITLE
Option DisableDownloadTimeout à rajouter dans pacman.conf 

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/archlinux-install#35]
Re,
Je suppose que le parallel download est activé dans pacman.conf
Il en résulte que pour quelqu'un ( comme moi) avec une faible connexion et un mauvais ping... L'installation échoue.
Pourrais-tu rajouter cette commande dans pacman.conf ?

Merci

**Comment by Rawleenc** [comment]
Re,

C'est effectivement une bonne idée de façon générale je pense. Ne serait-ce pas également une bonne idée de demander à l'utilisateur s'il souhaite avoir le parallel download de pacman ou pas ? Quel est le ressenti à l'utilisation du script avec une faible connexion ? Est-ce que le parallel download n'aurait pas un impact négatif sur le temps de téléchargement dans ce cas ?

Merci !

**Comment by Rawleenc** [comment]
ça marche, je laisse donc le parallel download à 5 pour tout le monde étant donné que ce n'est pas impactant avec en plus l'option DisableDownloadTimeout.

**Comment by Neo-29** [comment]
Super !
Je testerai quand ce sera prêt. Merci beaucoup.

**Comment by Rawleenc** [comment]
Bonsoir, 

L'ajout de l'option DisableDownloadTimeout au pacman.conf est disponible sur la branche de développement.

N'hésite pas à fermer cette issue :wink:

**Comment by Neo-29** [comment]
ça ne passe pas....
La commande de tri de miroirs est peut-être à revoir...
![image](https://user-images.githubusercontent.com/90937180/169283148-d5dfc2c4-6b6e-4d9a-8d1a-0286c41ed31e.png)

**Comment by Rawleenc** [comment]
Bonjour,
L'option a bien été ajoutée à la fois dans le pacman.conf du système live et dans le pacman.conf du système monté.
Voici la commande de tri utilisée par le script : 
```bash
reflector --save /etc/pacman.d/mirrorlist --threads $(nproc --all) --protocol https --age 12 --country "FR" --fastest 10 --sort rate
```
L'option country est valorisé en fonction de la localisation du client.
Cette commande m'a l'air d'être la plus générale possible, je ne vois pas vraiment ce que je pourrais faire de plus...

**Comment by Neo-29** [comment]
L'option n'y est pas au démarrage sur l'iso. (pacman.conf) 
En le rajoutant bizarrement ça passe.

**Comment by Neo-29** [comment]
Après quasi aucune commande de tri passe chez moi car ça dépasse svt 5 sec.
Donc timeout à chaque fois.
Ça ne gêne cependant pas après car l'installation s'effectue correctement

**Comment by Rawleenc** [comment]
Au pire en lançant le script une fois sur un environnement live tu peux vérifier après l'exécution l'état du pacman.conf après modification par le script

**Comment by Rawleenc** [comment]
Après l'échec ou la réussite de l'installation tu peux regarder le pacman.conf du système live, donc selui avant chroot, et si tu remontes les partitions du système installé tu peux regarder le pacman.conf du système installé qui a normalement été modifié juste avant l'exécution de la seconde commande pacman

**Comment by Neo-29** [comment]
> Après l'échec ou la réussite de l'installation tu peux regarder le pacman.conf du système live, donc selui avant chroot, et si tu remontes les partitions du système installé tu peux regarder le pacman.conf du système installé qui a normalement été modifié juste avant l'exécution de la seconde commande pacman

C'est effectivement une possibilité.
Ou alors j'ai pas eu de bol la première fois ?
A voir.

Je clôturerai après vérification.

**Comment by Neo-29** [comment]
Pacman.conf ok après récupération du script.
Probablement un pb ponctuel de connexion.

Je clôture

**Comment by Rawleenc** [comment]
Bonsoir,

Je réouvre cette issue parce qu'après réflexion je ne pense pas que ça soit une excellente idée d'activer cette option pour tout le monde. ça pourrait empêcher pacman de changer de miroir en cas de problèmes serveur.

Une meilleure idée je pense serait de copier le pacman.conf du système live dans le système monté, ce faisant l'utilisateur est libre de modifier la config pacman comme il veut et elle sera reprise telle quelle par le script, comme ça ce n'est pas impactant pour tout le monde.

**Comment by Neo-29** [comment]
Ça oblige donc à le modifier manuellement avant ? 🤔

**Comment by Rawleenc** [comment]
Oui, mais comme tu l'as dit toi même, ton cas est une exception, c'est relativement rare d'avoir une connexion si faible que pacman en arrive à timeout systématiquement. 😅

Et puis a l'inverse, c'est bien moins acceptable que pacman échoue une installation sur un poste fibré en cas de problème serveur parce qu'il n'avait pas le droit de timeout.

**Comment by Neo-29** [comment]
Ah non non... Mon cas n'est pas une exception !
C'est pas pour rien que endeavour os l'a intégré d'office

**Comment by Neo-29** [comment]
Moi sans cette option aucune possibilité d'installation.
Et ça ne change pas le tri des miroirs chez moi.
Par contre di quelqu'un rencontre ce pb, il nr saura pas forcément d'où cela vient et pourquoi l'installation échoue

**Comment by Rawleenc** [comment]
J'entends bien, le problème que j'ai c'est que cette option est susceptible de faire échouer l'installation pour les personnes ayant une bonne connexion, d'où ma réflexion

**Comment by Rawleenc** [comment]
Bon, je vais laisser cette option par défaut et si un jour je rencontre un problème d'échec d'installation a cause de mirror défectueux j'aviserais

**Comment by Neo-29** [comment]
> J'entends bien, le problème que j'ai c'est que cette option est susceptible de faire échouer l'installation pour les personnes ayant une bonne connexion, d'où ma réflexion

J'ai au moins 2 collègues qui ont testé sans pb pour le moment

**Comment by Neo-29** [comment]
> Oui, mais comme tu l'as dit toi même, ton cas est une exception, c'est relativement rare d'avoir une connexion si faible que pacman en arrive à timeout systématiquement. 😅
> 
> Et puis a l'inverse, c'est bien moins acceptable que pacman échoue une installation sur un poste fibré en cas de problème serveur parce qu'il n'avait pas le droit de timeout.

En passant, je suis en box4g et crois moi même avec quelquefois 24mo en download... J'ai un timeout.
Tu remercieras red by SFR 🙂😉😉😉

**Comment by Rawleenc** [comment]
Ça question se pose aussi pour le parallel download, est ce que c'est une bonne idée de le mettre par défaut ou pas

**Comment by Neo-29** [comment]
Un dev arch a expliqué que ce n'est pas activé pqr défaut car ca peut surcharger les serveurs.
Apres... 🤔🙂

**Comment by Neo-29** [comment]
Par contre.. J'ai de gros soucis au niveau du tri des miroirs avec cette commande.
Est-il possible d'accéder au fichier de config pour changer " on the fly" et tester une autre commande reflector ?

**Comment by Neo-29** [comment]
En fonction des pays ça pose souci.
Suis sur un groupe telegram où le pb revient souvent.
Pour moi les 10 plus rapides et plus récents c'est plus efficace.
D'ailleurs sur Anarchy Installer on est revenu en arrière sur cette commande reflector.
Du coup -f10 -l10

**Comment by Rawleenc** [comment]
Je vais faire des tests

**Comment by Neo-29** [comment]
Oui.. C'est le mieux.. Sinon tout fonctionne très bien.

J'avais une suggestion aussi pour le choix d'un gestionnaire de démarrage.
Souhaites tu que j'ouvre une autre issue ?
PS : je vais certainement faire une petite vidéo demo promotion de ton installateur sur notre groupe 😊

**Comment by Rawleenc** [comment]
Ça par contre ça demanderais bien plus de travail de permettre le choix d'un autre gestionnaire de démarrage.

C'est pas une mauvaise idée mais ça sera au minimum pour la prochaine version, la 3.4.0 voir plus tard, il faut que je réfléchisse à un système générique qui prennent en compte si on est en BIOS ou en UEFI et quand je le développerais j'ajouterais en première et unique alternative, systemd-boot.

L'idée étant ensuite d'en rajouter progressivement comme le système de choix du format de partitions.

Pour l'instant j'aimerais sortir la 3.3.0, il serait grand temps... As tu pu tester les messages d'aide d'ailleurs ?

**Comment by Neo-29** [comment]
> Ça par contre ça demanderais bien plus de travail de permettre le choix d'un autre gestionnaire de démarrage.
> 
> C'est pas une mauvaise idée mais ça sera au minimum pour la prochaine version, la 3.4.0 voir plus tard, il faut que je réfléchisse à un système générique qui prennent en compte si on est en BIOS ou en UEFI et quand je le développerais j'ajouterais en première et unique alternative, systemd-boot.
> 
> L'idée étant ensuite d'en rajouter progressivement comme le système de choix du format de partitions.
> 
> Pour l'instant j'aimerais sortir la 3.3.0, il serait grand temps... As tu pu tester les messages d'aide d'ailleurs ?
Pour les gestionnaires de démarrage c'est noté.. Et je comprends tout à fait. 
Pour les messages d'aide, c'est testé et ça fonctionne très bien.

**Comment by Rawleenc** [comment]
Bonsoir,

Suite à plusieurs tests, la commande reflector me fournissant les miroirs au débits les plus élevé est la suivante : 
```bash
reflector --verbose -phttps -f10 -l10 --sort rate -a12 --save /etc/pacman.d/mirrorlist
```
Le filtre -a2 étant trop court pour fetch les miroirs les plus rapide, j'ai choisi -a12, 12h étant un durée acceptable et permet de fetch des miroirs très rapide.

Qu'en penses-tu ?

**Comment by Neo-29** [comment]
Pour moi c'est parfait.
Je referai des tests demain.
Un membre de mon groupe a testé la branche dev.
Convaincu. Très bon retours.

**Comment by Rawleenc** [comment]
Ok, je viens de refaire un test, finalement le filtre -a2 me donne des miroirs encore plus rapide.

Je vais donc conserver ce filtre.

Je suis ravi que le script plaise ! 😁

**Comment by Rawleenc** [comment]
J'atteins les 100Mo/s en constant chez moi avec ces filtres c'est vraiment excellent, merci beaucoup pour ta suggestion !
