### ISSUE TITLE
Suggestions de clarifications installation

### ISSUE THREAD

**Issue by Neo-29** [Rawleenc/archlinux-install#36]
J'ai pensé à 2 3 améliorations

- petit texte court pour expliquer à quoi GRML correspond
- idem pour ce que représente les polices principales 
- idem pour expliquer en quelques mots ce qu'est "le support de fichiers principaux" 
- idem pour zRAm ( je le sais mais peut être pas tout le monde) 

Le reste est nickel

**Comment by Rawleenc** [comment]
Je peux étoffer le README à la limite

**Comment by Neo-29** [comment]
> Ça va peut-être faire trop chargé en informations non ?

Juste 2 3 mots à chaque ligne.. Ça devrait le faire 😉🙂

**Comment by Rawleenc** [comment]
Je vais ajouter un comportement générique permettant d'afficher un message d'aide si l'utilisateur entre 'h' au lieu de 'o' ou 'n' à une question

**Comment by Neo-29** [comment]
> Je vais ajouter un comportement générique permettant d'afficher un message d'aide si l'utilisateur entre 'h' au lieu de 'o' ou 'n' à une question

Excellente idée !

**Comment by Neo-29** [comment]
Hors sujet rapide.
J'administre un groupe arch sur Facebook.
On serait ravis que tu en fasse partie.
Tu me trouveras ( si tu y es) sur Fb à Neo Twenty-Nine
Contacte moi si tu le souhaites.

**Comment by Rawleenc** [comment]
Bonsoir ! 

Je ne suis pas sûr Facebook désolé ^^' Je suis assez contre cette plateforme.

Quoi qu'il en soit, la fonctionnalité des messages d'aides pour les questions est disponible sur la branche de développement !

**Comment by Rawleenc** [comment]
J'en ai profité pour rajouter du pattern matching pour vérifier la saisie du nom d'utilisateur afin de ne plus pouvoir saisir n'importe quoi par erreur.

**Comment by Neo-29** [comment]
> Bonsoir !
> 
> Je ne suis pas sur Facebook désolé ^^' Je suis assez contre cette plateforme.
> 
> Quoi qu'il en soit, la fonctionnalité des messages d'aides pour les questions est disponible sur la branche de développement !

C'est noté pour Facebook. Je comprends.

Merci pour la fonctionnalité d'aide !

**Comment by Neo-29** [comment]
Ok. L'aide fonctionne très bien.
Je clôture
